import 'dart:convert';
import 'dart:io';

/// Run from app/: dart run tool/generate_case_folding.dart
/// Unicode data is build-time input only; the app works entirely offline.
Future<void> main() async {
  final client = HttpClient();
  try {
    final request = await client.getUrl(
      Uri.parse('https://www.unicode.org/Public/17.0.0/ucd/CaseFolding.txt'),
    );
    final response = await request.close();
    if (response.statusCode != HttpStatus.ok) {
      throw StateError('Unicode download failed: ${response.statusCode}');
    }
    final source = await response.transform(utf8.decoder).join();
    if (!source.startsWith('# CaseFolding-17.0.0.txt')) {
      throw StateError('Unexpected Unicode version');
    }
    final output = StringBuffer(
      '// Generated by tool/generate_case_folding.dart; do not edit.\n'
      '// Unicode 17.0.0 full default case folding (C + F, excluding Turkic T).\n'
      '// Copyright Unicode, Inc. See tool/unicode-LICENSE.txt.\n'
      'const unicodeCaseFolding = <int, String>{\n',
    );
    for (final line in source.split('\n')) {
      final fields = line
          .split('#')
          .first
          .split(';')
          .map((v) => v.trim())
          .toList();
      if (fields.length < 3 || (fields[1] != 'C' && fields[1] != 'F')) continue;
      final mapping = fields[2].split(' ').map((v) => '\\u{$v}').join();
      output.writeln("  0x${fields[0]}: '$mapping',");
    }
    output.writeln('};');
    await File('lib/shared/journal/unicode_case_folding.g.dart')
        .writeAsString(output.toString());
  } finally {
    client.close(force: true);
  }
}
